version: '3'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    tty: true
    command: npm run dev
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true
