# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: インストール
      run: npm ci
      working-directory: ./client
    - name: Run Jest
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
      working-directory: ./client
      env:
        CI: true
    - run: npm run test:e2e
      working-directory: ./client
      env:
        BASE_URL: https://uu-circle20.firebaseapp.com
        CI: true
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREEMET_ID: ${{ secrets.FIREBASE_MEASUREEMET_ID }}
